#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    #n = int(input())
    #arr = input().split()
    p = 0
    m = 0
    z = 0
    for i in range(n):
        if (arr[i] > 0):
            p = p+1
        if (arr[i] < 0):
            m = m+1
        if (arr[i] == 0):
            z = z+1
    print(f"{p/n:.6f}")
    print(f"{m/n:.6f}")
    print(f"{z/n:.6f}")

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
