#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'counterGame' function below.
#
# The function is expected to return a STRING.
# The function accepts LONG_INTEGER n as parameter.
#

def counterGame(n):
    # Write your code here
    c = 1 # counter
    while(n>1):
        x = math.log(n,2)
        if(x%1 == 0):  # checking whether x has decimal part or not.
            n = n//2 # or n/2
            c = c+1
        else:
            n = n - 2**math.floor(x)
            c = c+1
    if(c%2==0):
        return "Louise"
    else:
        return "Richard" # n==1 case is handled automatically.
                
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        result = counterGame(n)

        fptr.write(result + '\n')

    fptr.close()
