#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pageCount' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER p
#

def pageCount(n, p):
    # Write your code here
    front_flipcount = math.ceil((p-1)/2)
    back_flipcount = math.floor((n-p)/2)
    if(n%2 != 0 or (n%2==0 and n-p!=1)):
        if(front_flipcount<=back_flipcount):
            return front_flipcount
        else:
            return back_flipcount
    else: ##cases when n is even and n-p=1
        if(front_flipcount<=back_flipcount+1):
            return front_flipcount
        else:
            return back_flipcount+1

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    p = int(input().strip())

    result = pageCount(n, p)

    fptr.write(str(result) + '\n')

    fptr.close()
