#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gridChallenge' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING_ARRAY grid as parameter.
#

def gridChallenge(grid):
    # Write your code here 
    for i in range(len(grid)):
        #print(grid[i])
        grid[i] = ''.join(sorted(grid[i]))
    col = []
    for j in range(len(grid[0])):
        col.append([row[j] for row in grid]) #Accessing columns in a 2D list.
        #print(col[j])
        #x = sorted(col[j]) #
        if(col[j]==sorted(col[j])): #using sorted() instead of .sort() as we don't want to update col[j] because it will result in wrong answers.
            continue
        else:
            return('NO')
            break
    return('YES')

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        grid = []

        for _ in range(n):
            grid_item = input()
            grid.append(grid_item)

        result = gridChallenge(grid)

        fptr.write(result + '\n')

    fptr.close()
