#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'twoArrays' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. INTEGER k
#  2. INTEGER_ARRAY A
#  3. INTEGER_ARRAY B
#

def twoArrays(k, A, B):
    # Write your code here
    n = len(A) # or len(B)
    Ad = sorted(A) # Ascending
    Bd = sorted(B, reverse=True) # Descending
    #By keeping one array ascending and other descending, we check all "i"th element sums combinations. If these fail to satisfy >=k, other combinations won't work anyway.
    
    # Note that ATQ "i"th element of both arrays need to be added and compared to k. That is, We have to look for same index in both arrays. 
    y = 0
    for i in range(n):
        if(Ad[i]+Bd[i] >= k):
            y = y+1       
    if(y == n):
        return "YES"
    else:
        return "NO"
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        first_multiple_input = input().rstrip().split()

        n = int(first_multiple_input[0])

        k = int(first_multiple_input[1])

        A = list(map(int, input().rstrip().split()))

        B = list(map(int, input().rstrip().split()))

        result = twoArrays(k, A, B)

        fptr.write(result + '\n')

    fptr.close()
