#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'sockMerchant' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY ar
#

def sockMerchant(n, ar):
    # Write your code here
    pairs = 0
    unpaired = set() #set contains only distinct elements, better & cleaner than list for this question.
    for i in ar: #More efficient way of solving- using set. Only uses single for loop instead of nested loops.
        if(i in unpaired):
            pairs += 1
            unpaired.remove(i)
        else:
            unpaired.add(i)
    return pairs

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
